# Generated by Django 4.1.6 on 2023-02-25 17:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته ')),
                ('depth', models.IntegerField(verbose_name='عمق')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.image')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='store.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('store_name', models.CharField(max_length=250, verbose_name='نام رستوران')),
                ('store_phone', models.CharField(help_text='به همراه پیش  شماره شهر', max_length=11, verbose_name='شماره رستوران')),
                ('is_verified', models.BooleanField(default=False, verbose_name='احراز هویت')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='هزینه پیک')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.IntegerField(verbose_name='شماره میز ')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('hour_price', models.IntegerField(verbose_name='هزینه هر ساعت')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tables', to='store.store')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='StoreDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_hours', models.JSONField()),
                ('business_lisence_img', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lisence', to='utils.image')),
                ('menu_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='utils.image')),
                ('national_card_img', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='utils.image')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Store', to='store.store')),
            ],
            options={
                'verbose_name': 'StoreDocument',
                'verbose_name_plural': 'StoreDocuments',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('hall_phone', models.CharField(help_text='به همراه پیش  شماره شهر', max_length=11, verbose_name='شماره سالن')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='accounts.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hall', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('contents', ckeditor.fields.RichTextField(verbose_name='جزییات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('is_verified', models.BooleanField(default=False)),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img', to='utils.image')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.store')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
            },
        ),
    ]
