# Generated by Django 4.1.6 on 2023-02-25 17:45

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp
import utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=storages.backends.ftp.FTPStorage(), upload_to=utils.models.ftp_upload_to)),
                ('alt', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_title', models.CharField(max_length=256)),
                ('arp_price', models.PositiveIntegerField(default=1000)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('fav_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_icon', to='utils.image')),
                ('nav_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_icon', to='utils.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
